language: ruby
sudo: false
cache: bundler
bundler_args: --without console benchmarks
script:
  - bundle exec rake
rvm:
  - 2.1.10
  - 2.2.5
  - 2.3.1
  - rbx-2
  - jruby-9.1.1.0
env:
  global:
    - JRUBY_OPTS='--dev -J-Xmx1024M'
matrix:
  allow_failures:
    - rvm: rbx-2

notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/19098b4253a72c9796db
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
